# Geocoding Plots

Refrence 
- https://towardsdatascience.com/geocode-with-python-161ec1e62b89
- https://alysivji.github.io/getting-started-with-folium.html

In [1]:
# !pip install geopandas
# !pip install geopy
# !pip install folium

In [2]:
#import geopandas as gpd
import geopy
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import matplotlib.pyplot as plt
import folium
from folium.plugins import FastMarkerCluster, HeatMap
import pandas as pd

## Geocoding a single address

In [3]:
locator = Nominatim(user_agent="myGeocoder")
location = locator.geocode("India Gate, Delhi, India")

In [4]:
location.address

'India Gate, Rajpath, Pandara Park, New Delhi, Chanakya Puri Tehsil, Delhi, 020626, India'

In [6]:
lat,long = location.latitude, location.longitude
lat,long

(28.6128806, 77.2295975)

In [7]:
#created a map object
map1 = folium.Map(
    location=[lat,long],
    tiles='cartodbpositron',
    zoom_start=20,     #how to zoom in zoom out cirxle
)
folium.CircleMarker(location=[lat,long]).add_to(map1)    #place circle at long,lat


In [8]:
map1

## Geocoding multiple address

In [9]:
df = pd.read_csv("zomato.csv", encoding='latin-1')

Restaurant ID         Restaurant Name  Country Code              City  \
0        6317637        Le Petit Souffle           162       Makati City   
1        6304287        Izakaya Kikufuji           162       Makati City   
2        6300002  Heat - Edsa Shangri-La           162  Mandaluyong City   
3        6318506                    Ooma           162  Mandaluyong City   
4        6314302             Sambo Kojin           162  Mandaluyong City   

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...   
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2  Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3  Third Floor, Mega Fashion Hall, SM Megamall, O...   
4  Third Floor, Mega Atrium, SM Megamall, Ortigas...   

                                     Locality  \
0   Century City Mall, Poblacion, Makati City   
1  Little Tokyo, Legaspi Village, Makati City   
2  Edsa Shangri-La, Ortigas, Mandaluyong City   
3      SM Megamall, Ortigas, Mandaluyong City   
4      SM Megamall, Ortigas, Mandaluyong City   

                                    Locality Verbose   Longitude   Latitude  \
0  Century City Mall, Poblacion, Makati City, Mak...  121.027535  14.565443   
1  Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101  14.553708   
2  Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831  14.581404   
3  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475  14.585318   
4  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508  14.584450   

                           Cuisines  ...          Currency Has Table booking  \
0        French, Japanese, Desserts  ...  Botswana Pula(P)               Yes   
1                          Japanese  ...  Botswana Pula(P)               Yes   
2  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)               Yes   
3                   Japanese, Sushi  ...  Botswana Pula(P)                No   
4                  Japanese, Korean  ...  Botswana Pula(P)               Yes   

  Has Online delivery Is delivering now Switch to order menu Price range  \
0                  No                No                   No           3   
1                  No                No                   No           3   
2                  No                No                   No           4   
3                  No                No                   No           4   
4                  No                No                   No           4   

   Aggregate rating  Rating color Rating text Votes  
0               4.8    Dark Green   Excellent   314  
1               4.5    Dark Green   Excellent   591  
2               4.4         Green   Very Good   270  
3               4.9    Dark Green   Excellent   365  
4               4.8    Dark Green   Excellent   229  

[5 rows x 21 columns]

In [10]:
df.head()

Restaurant ID         Restaurant Name  Country Code              City  \
0        6317637        Le Petit Souffle           162       Makati City   
1        6304287        Izakaya Kikufuji           162       Makati City   
2        6300002  Heat - Edsa Shangri-La           162  Mandaluyong City   
3        6318506                    Ooma           162  Mandaluyong City   
4        6314302             Sambo Kojin           162  Mandaluyong City   

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...   
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2  Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3  Third Floor, Mega Fashion Hall, SM Megamall, O...   
4  Third Floor, Mega Atrium, SM Megamall, Ortigas...   

                                     Locality  \
0   Century City Mall, Poblacion, Makati City   
1  Little Tokyo, Legaspi Village, Makati City   
2  Edsa Shangri-La, Ortigas, Mandaluyong City   
3      SM Megamall, Ortigas, Mandaluyong City   
4      SM Megamall, Ortigas, Mandaluyong City   

                                    Locality Verbose   Longitude   Latitude  \
0  Century City Mall, Poblacion, Makati City, Mak...  121.027535  14.565443   
1  Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101  14.553708   
2  Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831  14.581404   
3  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475  14.585318   
4  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508  14.584450   

                           Cuisines  ...          Currency Has Table booking  \
0        French, Japanese, Desserts  ...  Botswana Pula(P)               Yes   
1                          Japanese  ...  Botswana Pula(P)               Yes   
2  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)               Yes   
3                   Japanese, Sushi  ...  Botswana Pula(P)                No   
4                  Japanese, Korean  ...  Botswana Pula(P)               Yes   

  Has Online delivery Is delivering now Switch to order menu Price range  \
0                  No                No                   No           3   
1                  No                No                   No           3   
2                  No                No                   No           4   
3                  No                No                   No           4   
4                  No                No                   No           4   

   Aggregate rating  Rating color Rating text Votes  
0               4.8    Dark Green   Excellent   314  
1               4.5    Dark Green   Excellent   591  
2               4.4         Green   Very Good   270  
3               4.9    Dark Green   Excellent   365  
4               4.8    Dark Green   Excellent   229  

[5 rows x 21 columns]

In [11]:
df_s = df.sample(50)

In [12]:
df_s

Restaurant ID                                    Restaurant Name  \
2306          96626  Jonathan's Kitchen - Holiday Inn Express & Suites   
6809       18432849                                    Smokey Flavours   
1267            157                                             Subway   
5141       18332076                        Kolhapuri Veg Non-Veg Foods   
9529        6001748                           Meôhur í_zí_elik Aspava   
6342       18244250                                             Gopala   
8856       18285723                                         Chai Thela   
5776         301927                                 Paratha Hi Paratha   
602          202507                                         Applebee's   
7230         304092                                Arora's Veg. Corner   
1429         304552                                                IZU   
633         3400072                       Dawat-e-Nawab - Radisson Blu   
2959       18471314                                     Me and My Cake   
1458       18462584                                    The Lost Mughal   
3904       18381236                              Al Forno by Aishwarya   
3860       18499482                                                TAG   
7680       18014109                                         Wah Ji Wah   
5407       18489819                                     Chinese Corner   
5638       18425178                              Al Meraj Chicken Shop   
5453           1041                                            Hot Pot   
1554           2760                               Vapour Pub & Brewery   
7322           7761                                    Cafe Coffee Day   
9490        6517568                                    Jamie's Italian   
5461           9427                                    Chacha Di Hatti   
5579       18466408                                         Desi Dhaba   
4260       18243438                                      Chaap Express   
478        17621744                                  Da Kao Restaurant   
5361         301110                                  Zaika Kathi Rolls   
8257       18421504                                  The Kebab Company   
7898           2402                                             Pakwan   
7766       18279461                                              Giani   
9270        2800128                         Sea Inn - Raju Gaari Dhaba   
2546        1600252                                         Chai Tapri   
5798       18462571                                        Happy Hours   
760         2600230                       Manohar Dairy And Restaurant   
9315        7001670                          Eight - The Langham Hotel   
2666       18421693                                     Cookie Shookie   
741        18366652                                             Onesta   
5264       18281964                                      Punjabi Mirch   
5385       18472695                                  Chinese Fast Food   
303        17375180                            Moonie's Texas Barbecue   
9291        7417455                                   Talaga Sampireun   
1628       18336543                                     The Burger Hub   
1710         309030                                  Hong Kong Express   
8105           9731                               Bansiwala Restaurant   
4305       18168125                                           Informal   
5375         309979                                   Green Chick Chop   
7864         303849                                   Mr. Crust Bakers   
5499         302715                                         Basil Tree   
281        17342770                                      L. May Eatery   

      Country Code         City  \
2306             1    Hyderabad   
6809             1    New Delhi   
1267             1      Gurgaon   
5141             1    New Delhi   
9529           208       Ankara   
6342             1   

In [14]:
#folium Map
map2 = folium.Map(
    location=[28.556828,77.174210],
    tiles='cartodbpositron',
    zoom_start=12,
)

#making circle for every hotel
df_s.apply(lambda row:folium.CircleMarker(location=[row["Latitude"], row["Longitude"]]).add_to(map2), axis=1)
map2

In [38]:
df_s = df.sample(500)

In [15]:
map2 = folium.Map(
    location=[28.556828,77.174210],
    tiles='cartodbpositron',
    zoom_start=12,
)
df_s.apply(lambda row:folium.CircleMarker(location=[row["Latitude"], row["Longitude"]]).add_to(map2), axis=1)
map2

## Plot Clustered points 

In [16]:
folium_map = folium.Map(location=[28.556828,77.174210],
                        zoom_start=12,
                        tiles='cartodbpositron')


FastMarkerCluster(data=list(zip(df_s['Latitude'].values, df_s['Longitude'].values))).add_to(folium_map)
folium.LayerControl().add_to(folium_map)
folium_map

In [20]:
df['Latitude'].values

array([14.565443  , 14.553708  , 14.581404  , ..., 41.05581715,
       41.057979  , 40.98477563])

In [21]:
df_s['Longitude'].values


array([ 78.3475536 ,  77.19396817,  77.0814039 ,  77.2169065 ,
        32.86663333,  77.2908794 ,  77.3666722 ,  77.1365287 ,
        55.27430557,  77.1695908 ,  77.0990285 ,  78.057044  ,
         0.        ,  77.09335204,   0.        ,   0.        ,
        77.0611463 ,  77.1451213 ,  77.1707986 ,  77.1907078 ,
        77.0892792 ,  77.2195433 ,  28.068062  ,  77.1902762 ,
        77.2090968 ,  77.2460575 , -96.4173    ,  77.3292915 ,
        77.36600563,  77.074213  ,  77.16341134,  83.38285833,
         0.        ,  77.1357857 ,  77.434007  , 174.764078  ,
        77.3068421 ,  77.5709967 ,  77.2952184 ,  77.1919008 ,
       -83.927794  , 106.8335532 ,  77.0161752 ,  77.0395802 ,
        77.5127189 ,  77.220458  ,  77.1814052 ,  77.2014873 ,
        77.1469965 , -90.668164  ])

In [19]:
x=[1,2,3]
y=[4,5,6]

#to get this -->    [[1,4],[2,5],[3,6]]

#fori in range(len(a)):
   # c.append([a[i],b[i]])
             

        list(zip(a,b))


IndentationError: unexpected indent (<ipython-input-19-27441fa9ad4d>, line 10)

SyntaxError: invalid syntax (<ipython-input-22-c1479c2ac910>, line 1)

## Plot Heatmaps

In [23]:
#heatmap-> add another layer of colur of lop
folium_map = folium.Map(location=[28.556828,77.174210],
                        zoom_start=12,
                        tiles='cartodbpositron')


FastMarkerCluster(data=list(zip(df['Latitude'].values, df['Longitude'].values))).add_to(folium_map)
folium.LayerControl().add_to(folium_map)
folium_map

In [26]:
points = df[['Latitude', 'Longitude']].to_numpy()

In [27]:
points

array([[ 14.565443  , 121.027535  ],
       [ 14.553708  , 121.014101  ],
       [ 14.581404  , 121.056831  ],
       ...,
       [ 41.05581715,  29.03464001],
       [ 41.057979  ,  29.036019  ],
       [ 40.98477563,  29.02601603]])

In [28]:
folium_map = folium.Map(location=[28.556828,77.174210],
                        zoom_start=12,
                        tiles='cartodbpositron')

In [30]:
folium_map.add_child(HeatMap(points, radius=15))