In [1]:
#NumPy stands for Numerical Python
#NumPy is a python library used for working with arrays.
#It also has functions for working in domain of linear algebra, fourier transform, and matrices.

#NumPy aims to provide an array object that is up to 50x faster that traditional Python lists.

#The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.


import numpy as np

In [2]:
#NumPy is used to work with arrays. The array object in NumPy is called ndarray.
#We can create a NumPy ndarray object by using the array() function.

arr=np.array([1,2,3,4,5,6,7,8])     #a 1-D array
print(arr)

[1 2 3 4 5 6 7 8]


In [5]:
#5 dimensions and verify that it has 5 dimensions:
a1= np.array([1,2,3,4], ndmin=5)
print(a1)

[[[[[1 2 3 4]]]]]


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
#0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

ar= np.array(12)  #0-D array with value 12
print(ar)
print(ar.ndim)

12
0


In [10]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
#Access the 5th element on 2nd dim:
print(arr[1,4])
print(arr[1,-2])

10
9


In [19]:
#Slicing in python means taking elements from one given index to another given index.
#We pass slice instead of index like this: [start:end].
#We can also define the step, like this: [start:end:step].
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[1:5])     #Slice elements from index 1 to index 5----result includes the start index, but excludes the end index
print(arr[-3:-1])


#the step value to determine the step of the slicing
print(arr[1:5:2])
print(arr[1:7:3])


#Slicing 2-D Arrays
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,2:4])
print(arr[1:3,2])


print(arr.dtype)

[2 3 4 5]
[6 7]
[2 4]
[2 5]
[8 9]
[8]
int32
